### ISSUE TITLE
installation - pub get failed

### ISSUE THREAD

**Issue by abulka** [luhluh-17/flutter-neucalcu#1]
Looking to install this on my mac on the Flutter dev channel, but getting a pub get error:

```
Because dartx >=0.2.0 <0.4.0 depends on path >=1.6.4 <1.7.0 and every version of flutter_test from sdk depends on path 1.7.0, dartx >=0.2.0 <0.4.0 is incompatible with flutter_test from sdk.
So, because neucalcu depends on both flutter_test any from sdk and dartx ^0.3.0, version solving failed.

...

SLVR:   ! dartx ^0.3.0 is satisfied by dartx ^0.3.0
SLVR:   ! which is caused by "neucalcu depends on dartx ^0.3.0"
SLVR:   ! thus: version solving failed
SLVR: Version solving took 0:00:03.039692 seconds.
    | Tried 1 solutions.
FINE: Resolving dependencies finished (3.1s).
ERR : Because no versions of dartx match >0.3.0 <0.4.0 and dartx 0.3.0 depends on path >=1.6.4 <1.7.0, dartx ^0.3.0 requires path >=1.6.4 <1.7.0.
    | And because every version of flutter_test from sdk depends on path 1.7.0, dartx ^0.3.0 is incompatible with flutter_test from sdk.
    | So, because neucalcu depends on both flutter_test any from sdk and dartx ^0.3.0, version solving failed.
FINE: Exception type: SolveFailure
FINE: package:pub/src/solver/version_solver.dart 312:5   VersionSolver._resolveConflict
    | package:pub/src/solver/version_solver.dart 133:27  VersionSolver._propagate
    | package:pub/src/solver/version_solver.dart 97:11   VersionSolver.solve.<fn>
    | ===== asynchronous gap ===========================
    | dart:async                                         Future.catchError
    | package:pub/src/utils.dart 113:52                  captureErrors.wrappedCallback
    | package:stack_trace                                Chain.capture
    | package:pub/src/utils.dart 126:11                  captureErrors

    | package:pub/src/command_runner.dart 193:13         PubCommandRunner.runCommand

---- End log transcript ----
pub get failed (1; ---- End log transcript ----)
exit code 1
```

Any thoughts please?  I am a beginner in Flutter but have a working development environment and have created quite a few test flutter apps.

P.S. This calc project seems to cause vscode to show all packages with red underlines, incl `import 'package:flutter/material.dart';` e.g. a similar issue is discussed at https://github.com/flutter/flutter/issues/19384 in other projects.  However my other flutter projects are ok.  Flutter doctor is OK.

**Comment by luhluh-17** [comment]
@abulka 

There are two issues with what happened.
Red lines on material.dart indicates that you have not yet run pub get and you were unable to run pub get because there are conflicting package dependencies.

I just tried switching to the dev channel and it broke my app. I could only guess they might have introduced some breaking changes in the dependencies. 

I suggest you switch back to the stable channel if you want to run my project.

**Comment by luhluh-17** [comment]
I would like to also point out in my pubspec.yaml file I'm overriding dartx to v0.3.0 because hive has some packages that depend on that version and this is a known issue.
